/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PlayersRouteImport } from './routes/players/route'
import { Route as ComputeRouteImport } from './routes/compute/route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PlayersRouteRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRoute,
} as any)

const ComputeRouteRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRoute
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRouteRoute
  '/players': typeof PlayersRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compute': typeof ComputeRouteRoute
  '/players': typeof PlayersRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/compute': typeof ComputeRouteRoute
  '/players': typeof PlayersRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compute' | '/players'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compute' | '/players'
  id: '__root__' | '/' | '/compute' | '/players'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeRouteRoute: typeof ComputeRouteRoute
  PlayersRouteRoute: typeof PlayersRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeRouteRoute: ComputeRouteRoute,
  PlayersRouteRoute: PlayersRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/compute",
        "/players"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/compute": {
      "filePath": "compute/route.tsx"
    },
    "/players": {
      "filePath": "players/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
